name: Code Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer Dependencies
        run: composer install

      - name: Run tests and generate code coverage report
        run: vendor/bin/phpunit --coverage-clover /tmp/coverage/coverage.xml

      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: /tmp/coverage

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install xml2js

      - name: Parse XML and get node property
        id: parse-xml
        run: |
            const xml2js = require('xml2js');
            const fs = require('fs');

            // Read the XML file
            const xmlData = fs.readFileSync('/tmp/coverage/coverage.xml', 'utf8');

            // Parse the XML
            xml2js.parseString(xmlData, (err, result) => {
              if (err) {
                console.error(err);
                process.exit(1);
              }

              // Access the property value from the parsed XML
              const propertyValue = result.coverage.project[0].metrics[0].coveredstatements[0];

              console.log(`The property value is: ${propertyValue}`);
            });
