name: Code Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer Dependencies
        run: composer install

      - name: Run tests and generate code coverage report
        run: vendor/bin/phpunit --coverage-clover /tmp/coverage/coverage.xml

      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: /tmp/coverage

      - name: Check code coverage
        uses: actions/github-script@v5
        with:
          script: |
            const { readFileSync } = require('fs');
            const { parse } = require('xml-parser-js');

            const xml = readFileSync('/tmp/coverage/coverage.xml', 'utf8');
            const parsedXml = parse(xml);

            console.log(parsedXml.node.name);
