name: Code Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install PHPUnite
        run: composer global require phpunit/phpunit:10
        shell: bash

      - name: Run tests and generate code coverage report
        run: phpunit --coverage-html /tmp/coverage

      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: /tmp/coverage

      - name: Check code coverage
        uses: actions/github-script@v5
        with:
          script: |
            const coverage = require('./code-coverage/index.html');
            if (coverage.total.lines.covered / coverage.total.lines * 100 < 80) {
              throw new Error('Code coverage must be at least 80%');
            }
