name: PHPUnit Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    name: PHPUnit with Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer Dependencies
        run: composer install

      - name: Run PHPUnit with Code Coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload PHPUnit Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.xml

      - name: Fail if Code Coverage is Less than 99%
        run: |
          if [ -f "coverage.xml" ]; then
            coverage=$(sed -n 's/.*<coverage.*line-rate="\([0-9.]*\)".*/\1/p' coverage.xml)
            if (( $(echo "$coverage < 0.99" | bc -l) )); then
              echo "Code coverage is less than 80%. Current coverage: $coverage"
              exit 1
            else
              echo "Code coverage is acceptable: $coverage"
            fi
          fi
