name: Prevent push if tests directory is modified or deleted

on: [push]

jobs:
  check-tests-directory:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check if tests directory is modified or deleted
        run: |
          if [[ $(git diff --name-only HEAD@{1} HEAD | grep -q "/tmp/tests") ]]; then
            echo "Tests directory is modified or deleted. Push aborted."
            exit 1
          fi
