name: Fail push if tests directory is modified or deleted

on: [ push ]

jobs:
  fail-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        run: git diff --name-only --diff-filter=AM HEAD^1 HEAD

      - name: Fail push if tests directory is modified or deleted
        run: |
          if [[ "$(git ls-files -z tests)" != "" ]]; then
            echo "Tests directory is modified or deleted. Failing push."
            exit 1
          fi